name: flutter_food
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Networking
  http: ^1.2.1

  # File Download & PDF Invoice Support
  path_provider: ^2.1.4
  open_filex: ^4.3.3

  # UI & Icons
  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.2

  # Toast Notifications
  fluttertoast: ^8.2.6

  # Local Storage
  shared_preferences: ^2.3.2

  # Date Formatting
  intl: ^0.19.0

  # Gorgeous Sweet Alerts
  cool_alert: ^2.0.1
  awesome_dialog: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/bkash.png
    - assets/images/rocket.png
    - assets/images/cash.png
    - assets/images/food_banner.png   # ✅ added for dashboard banner
    - assets/delivery.gif
    - assets/menu.gif
    - assets/approve.gif
    - assets/offers/weekend1.jpg
